### ISSUE TITLE
Print, share, RSS, ICS

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#117] opened 2013-09-03 13:58 UTC
Are all these functions implemented?

**Comment by klokan** [comment] 2013-09-06 18:15
Yes. This should be already implemented, but we will check again. There may be regression with the last changes on the website.

**Comment by JackuB** [comment] 2013-09-08 16:28
RSS is not working because of lockdown
ICS is working

**Comment by klokan** [comment] 2013-09-11 07:01
Closing - if there is an report of issue we reopen or create a new ticket where the issue is described.

**Closed as completed by klokan** 2013-09-11 07:01 UTC
Labels: WEB
