### ISSUE TITLE
Sorting of records with identical bounding-boxes 

### ISSUE THREAD

**Issue by ghost** [klokantech/kartenportal-tickets#283] opened 2014-10-16 13:41 UTC
FROM:zb
Records with identical bounding-boxes in MARC field 034 shoud be sorted in the Trefferliste according to the year in descending order. 

See also old issue #68 (2013-05-31).

**Comment by klokan** [comment] 2014-10-16 16:21
We cannot reproduce the error.

The example in #68, e.g. http://search.kartenportal.ch/#bbox=73.49941360000002,18.153521599999994,134.77280955959213,53.56097399999999&q=atlas&date_from=1950&date_to=9999&scale_from=&scale_to=&libraries=

produces expected order, because there is always only a few maps with exactly the same bounding box, which are ordered, then comes another group with bounding box, which is slightly different.

No other example is provided, which would prove there is a bug. I suggest to close this ticket. Please comment, Markus.

**Comment by ghost** [comment] 2014-10-17 10:17
FROM:zb
It can be reproduced easily, although only in conjunction with sheets from map series. The sorting is fine with atlases and single sheets.

Just two examples for sheets from map series:

(1) http://search.kartenportal.ch/#bbox=9.025587738281274,46.09827044192284,9.254753737008059,46.20777079798444&q=title%3Ajorio&date_from=0&date_to=9999&scale_from=25000&scale_to=25000&libraries=&map=road

see screenshot where the Trefferliste shows the following editions from the Carta nazionale della Svizzera 1:25,000: 2014, 1998, 2004, 2008, 1990, 1962, 1985. All of these have the identical bounding-box (E 9°03'22"-E 9°17'10"/N 46°14'16"-N 46°07'35"). They should therefore be sorted in descending order like this: 2014, 2008, 2004, 1998, 1990, 1985, 1962.

[cid:image002.jpg@01CFEA04.40AB4A50]

(2) http://search.kartenportal.ch/#bbox=4.2828124999995225,46.88023210588238,12.282812455555131,50.012813644123945&q=&date_from=0&date_to=9999&scale_from=250000&scale_to=250000&libraries=&map=road see screenshot where the Trefferliste shows the following editions of sheet "Mulhouse": 1968, 1982, 1975. All of these have the identical bounding-box (E 6°00'-E 8°00'/N 48°00'-N 47°00'). Their order in the Trefferliste should be: 1982, 1975, 1968.

[cid:image006.jpg@01CFEA04.40AB4A50]

**Comment by klokan** [comment] 2014-10-21 16:15
Could you please submit these images to info@klokantech.com?

**Comment by keosak** [comment] 2014-10-22 14:21
Previously, MapRank only sorted by date inside each series and its sheet. I have extended the sort to all records with the same similarity. Please verify that the results are now correct.

**Comment by ghost** [comment] 2014-10-24 07:54
FROM:zb
Tested and accepted.

**Closed as completed** 2014-10-24 08:38 UTC
Labels: @zb
