### ISSUE TITLE
Regular metadata import required (new bug?)

### ISSUE THREAD

**Issue by zb-markus** [klokantech/kartenportal-tickets#174] opened 2013-10-17 12:18 UTC
There is no metadata import since a few days. Please test whether this is the same bug as in #118 or a new one. Test records:

Lefkosia 1:7 500
NEBIS http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=009940587 (catalogued 2 Oct 2013)
Swissbib http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22221052763%22+IN+%5B4%5D&v=nose&l=de (dated 6 Oct 2013)
MapRank n/a

Tektonikarena Sardona 1:50 000
NEBIS http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=009962343 (catalogued 2 Oct 2013)
Swissbib http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22221949283%22+IN+%5B4%5D&v=nose&l=de (dated 16 Oct 2013)
MapRank http://suche.kartenportal.ch/#id=219628254 (NEBIS holdings missing, record provided at earlier date by Swisstopo etc.)

Vogels Karte von Mitteleuropa 1:500 000
NEBIS http://opac.nebis.ch/F/?local_base=NEBIS&CON_LNG=GER&func=find-b&find_code=SYS&request=009969898 (catalogued 10 Oct 2013)
Swissbib http://www.swissbib.ch/TouchPoint/perma.do?q=0%3D%22222287357%22+IN+%5B4%5D&v=nose&l=de (dated 12 Oct 2013)
MapRank n/a (record http://suche.kartenportal.ch/#id=197392075 is the civilian edition, but now the military edition has been catalogued and should show up as well)

**Comment by klokan** [comment] 2013-10-21 06:53
We are investigating this issue.

**Comment by keosak** [comment] 2013-10-21 11:49
This issue was caused by faulty configuration of the "cron" daemon. It is fixed now.

**Closed as completed by keosak** 2013-10-21 11:49 UTC
Labels: SEARCH

**Comment by zb-markus** [comment] 2013-10-22 10:50
Tested and accepted.
