### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#135] opened 2013-09-16 13:31 UTC
Kartenportal.CH Icon fills an column. There is not enough space left for the real  information part, the font in the hardcopy is to small.

![print](https://f.cloud.github.com/assets/4223790/1149062/e6722172-1ed3-11e3-88fb-824eebb1cd51.jpg)

**Comment by JackuB** [comment] 2013-09-16 17:34
1, printing is hard to control on responsive webdesign, as there are no clear (technical) rules to control and test printing styles across browsers

2, Page looks printed in horizontal mode - was it printed in horizontal or portrait view?

In portrait it (should) looks like this (I don't have setting to print page in horinzontal mode in Chrome)

![image](https://f.cloud.github.com/assets/1788727/1151101/769d01d8-1ef5-11e3-898c-182cce459ae0.png)

**Comment by ethbib-susanne** [comment] 2013-09-16 18:10
J will try again tomorrow. Maybe J find a way for propre printing.

**Comment by ethbib-susanne** [comment] 2013-09-17 07:40
J can only produce this layout. What happens when you leave out the logo. In my opinion it is not that important.

![printing](https://f.cloud.github.com/assets/4223790/1155333/065f5a20-1f6c-11e3-9566-cc10bf4b75c7.jpg)

Can you leave a bit more space between header information and content in the printing template?

**Comment by ethbib-susanne** [comment] 2013-09-17 07:40
Can you leave a bit more space between header information and content in the printing template?

**Comment by klokan** [comment] 2013-09-17 14:05
This is probably related to "Firefox 23.0" which Susanne is using.

**Comment by JackuB** [comment] 2013-09-24 21:58
I just physically printed page from Firefox (23.0.1) and it worked just fine (same layout as in Chrome preview above).

So I'm closing this as something I couldn't reproduce and my guess it, that above preview is affected by 60% scaling (visible in toolbar).

**Closed as completed by JackuB** 2013-09-24 21:58 UTC
Labels: WEB
