### ISSUE TITLE
Responsive problem

### ISSUE THREAD

**Issue by ethbib-susanne** [klokantech/kartenportal-tickets#178] opened 2013-10-23 09:04 UTC
Firefox 24.0

![responsive design](https://f.cloud.github.com/assets/4223790/1388609/1112ae32-3bc2-11e3-840e-0421c47a5021.jpg)

**Comment by JackuB** [comment] 2013-10-23 20:34
![image](https://f.cloud.github.com/assets/1788727/1393923/ae7d90a6-3c21-11e3-8abc-c30c4289ceb7.png)

![image](https://f.cloud.github.com/assets/1788727/1393929/b7eed6e0-3c21-11e3-92ee-f7d2327db642.png)

I really tried to reproduce this (also in Firefox 24) - break point (where layout changes) is set to 768px - so that on 767px window layout looks almost the same as on mobile, but on 768px it still looks almost like on desktop. I haven't found this behaviour on these two points...

Layout stay like your screenshot for about 0,5 seconds, then it renders correctly _(delay is there because of performance reasons)_

**Comment by JackuB** [comment] 2013-10-28 14:26
Closing as I couldn't reproduce nor received comments.

**Comment by klokan** [comment] 2013-10-28 14:43
Reproduced. Firefox 24.0 under Mac. Width of the `<html>` 765px. No errors in the JavaScript console.

![screen shot 2013-10-28 at 15 41 33](https://f.cloud.github.com/assets/59284/1420388/4504e720-3fdf-11e3-8837-2a0cff6fed24.png)

**Comment by klokan** [comment] 2013-10-28 14:55
Reproduced in latest Chrome (30.0.1599.101) under Mac.
`<html>` width 758 (probably without padding).

It seems the padding is what makes the troubles in the responsivnes definitions.

Screenshot:
![screen shot 2013-10-28 at 15 54 15](https://f.cloud.github.com/assets/59284/1420515/06f04176-3fe1-11e3-8a60-f50d96012ee5.png)

**Comment by JackuB** [comment] 2013-10-28 15:16
I still couldn't reproduce, but I just committed fix, which could fix it for you. Please test it.

**Comment by klokan** [comment] 2013-10-28 15:30
It is now fixed. Thank you.

**Closed as completed by klokan** 2013-10-28 15:30 UTC
